Выполнено ТЗ15:
Vladyak1/java-shareit pull request #2
Opened 2024-08-10 13:37 UTC by Vladyak1

- реализован функционал комментариев и бронирований

2024-08-11 07:06 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "ALL", required = false) String state) {
Если используем defaultValue = "ALL", то required = false уже избыточно. Если значение параметра в ендпоинт не поступит, то в случае с defaultValue оно свяжется со значением по умолчанию, а в случае required = false с null

2024-08-11 07:11 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @PostMapping
Для `@RestController` можно оформить методы менее многословно
   
```
@PostMapping
 public BookingDto create(@RequestHeader("X-Sharer-User-Id") Long userId,
                                             @RequestBody @Validated(ValidateWhile.Create.class) BookingRequestDto bookingRequestDto) {
        log.info("Вызов метода POST бронирования: userId={}, booking={}", userId, bookingRequestDto);
        return bookingService.saveBooking(userId, bookingRequestDto);
 }
```

2024-08-11 07:14 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
InMemory реализация больше не понадобится, удаляем из проекта

2024-08-11 07:21 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                Booking.builder()
А toModel маппера здесь не подойдет?

2024-08-11 07:31 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new RepositoryReceiveException("Такой вещи для бронирования нет"));
Не очень понятно почему здесь не найдено и такое исключение выбрасывается, а дальше тоже не найдено и другое исключение.
Вообще общая практика если ищем и не найдено кидать NotFoundException, тем более что обе ситуации в хендлере в NOT_FOUND превратятся.

2024-08-11 07:37 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new MyNotFoundException("Запрашивать бронирование можен только владелец, " +
Здесь не NotFoundException т.к. не выполняется бизнес-требование. Нужно другое какое нибудь исключение использовать (например ValidationException), которое затем в хандлере в HttpStatus.BAD_REQUEST обработается.

2024-08-11 07:38 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return switch (state) {
Лучше создать перечислимое

2024-08-11 07:44 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +  email VARCHAR(512) NOT NULL
Добавил бы на эту колонку ограничение по уникальности

2024-08-11 07:46 UTC, VadimZharkov requested changes
Можно улучшить

2024-08-11 08:20 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new MyNotFoundException("Запрашивать бронирование можен только владелец, " +
Заменено на BookingServiceException (BAD_REQUEST)

2024-08-11 08:22 UTC, Vladyak1 commented on src/main/resources/schema.sql
> +  email VARCHAR(512) NOT NULL
Добавил CONSTRAINT UQ_USER_EMAIL UNIQUE (email)

2024-08-11 08:23 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "ALL", required = false) String state) {
Понял, убрал required = false

2024-08-11 08:23 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
Удалил

2024-08-11 08:24 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new RepositoryReceiveException("Такой вещи для бронирования нет"));
Сделал автоматом, исправил на правильное

2024-08-11 08:24 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return switch (state) {
Не совсем понял формулировку и что нужно сделать

2024-08-11 08:27 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @PostMapping
Убрать ResponseEntity? Встретил случай, когда наоборот советуют его использовать, решил изучить и применить у себя

2024-08-11 08:27 UTC, Vladyak1 commented
Внёс изменения кроме двух замечаний

2024-08-12 04:49 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @PostMapping
Можно и так и так. На курсе рекомендуют тот, про который я написал. Но если ты про него знаешь и  ResponseEntity взял для того чтобы попробовать альтернативный способ, то это конечно хорошо и оставляй как сделал.

2024-08-12 04:52 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return switch (state) {
Лучше сделать enum для state и в switch использовать его вместо строк.

2024-08-12 13:53 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @PostMapping
Да, решил этот проект сделать с использованием ResponseEntity

2024-08-12 13:54 UTC, Vladyak1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return switch (state) {
Сделал по твоему совету, надеюсь правильно
Через enum действительно лучше, спасибо!

2024-08-12 15:54 UTC, closed without merging